In [5]:
import cv2
import numpy as np
import glob

In [6]:
data_path = glob.glob('/Users/waranthornchansawang/Desktop/RASH_INSPECTOR/Dataset/original_data/Allergy/AtopicDermatitis/arm/*.jpg')

new_path = '/Users/waranthornchansawang/Desktop/RASH_INSPECTOR/Dataset/renorm/AtopicDermatitis/arm2/norm_{}.jpg'

In [8]:
def resize(input_path, output_path):
    
    image_size = 224
    dim = (image_size, image_size)
    
    for i, img in enumerate(input_path):
        image = cv2.imread(img, -1)
        resized_image = cv2.resize(image, dim)
        cv2.imwrite(output_path.format(i), resized_image)

In [9]:
resize(data_path, new_path)

In [13]:
x=cv2.imread('/Users/waranthornchansawang/Desktop/RASH_INSPECTOR/Dataset/renorm/AtopicDermatitis/arm/norm_20.jpg')

In [14]:
print(x)

[[[255 176 105]
  [254 174 103]
  [248 170  99]
  ...
  [253 203 150]
  [253 203 150]
  [255 206 153]]

 [[255 176 105]
  [255 175 104]
  [251 171 100]
  ...
  [254 204 151]
  [253 203 150]
  [255 206 153]]

 [[255 174 103]
  [254 174 103]
  [251 171 100]
  ...
  [254 204 151]
  [252 202 149]
  [255 205 152]]

 ...

 [[203 113  25]
  [204 114  26]
  [205 115  27]
  ...
  [255 188 123]
  [255 187 122]
  [255 187 122]]

 [[202 112  24]
  [204 114  26]
  [205 115  27]
  ...
  [255 188 123]
  [252 185 122]
  [253 186 123]]

 [[202 112  24]
  [204 114  26]
  [206 116  28]
  ...
  [255 188 123]
  [251 184 121]
  [252 185 122]]]


In [15]:
y = cv2.imread('/Users/waranthornchansawang/Desktop/RASH_INSPECTOR/Dataset/renorm/AtopicDermatitis/arm2/norm_20.jpg')

In [16]:
print(y)

[[[255 185 122]
  [255 184 121]
  [252 181 118]
  ...
  [254 211 162]
  [253 210 161]
  [255 214 165]]

 [[255 185 122]
  [255 185 122]
  [253 182 119]
  ...
  [254 211 162]
  [253 210 161]
  [255 213 164]]

 [[255 182 120]
  [255 183 121]
  [252 181 118]
  ...
  [254 211 162]
  [252 209 160]
  [255 212 163]]

 ...

 [[209 130  51]
  [210 131  52]
  [210 131  52]
  ...
  [255 196 137]
  [255 195 136]
  [255 195 136]]

 [[209 129  52]
  [210 130  53]
  [211 131  54]
  ...
  [255 196 137]
  [253 195 136]
  [253 195 136]]

 [[208 128  51]
  [210 130  53]
  [212 132  55]
  ...
  [255 196 137]
  [253 195 136]
  [252 194 135]]]
