In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mping
from skimage import exposure
from skimage.util import random_noise
from skimage import transform

In [3]:
#for i, img in enumerate():   

In [16]:
#img = mping.imread('/Users/waranthornchansawang/Desktop/RASH_INSPECTOR/Dataset/ORGAN/step2_selected_data/bodyskin/AD/AD32.jpg')
img = mping.imread('/Users/waranthornchansawang/Desktop/RASH_INSPECTOR/Dataset/ORGAN/step0_original_data/AtopicDermatitis/bodyskin/AD32.jpg', -1)
print(img)

[[[252 254 251]
  [252 254 251]
  [252 254 251]
  ...
  [252 254 251]
  [252 254 251]
  [252 254 251]]

 [[252 254 251]
  [252 254 251]
  [252 254 251]
  ...
  [252 254 251]
  [252 254 251]
  [252 254 251]]

 [[252 254 251]
  [252 254 251]
  [252 254 251]
  ...
  [252 254 251]
  [252 254 251]
  [252 254 251]]

 ...

 [[171 151 140]
  [172 152 141]
  [172 154 142]
  ...
  [252 254 251]
  [252 254 251]
  [252 254 251]]

 [[168 150 138]
  [173 155 143]
  [164 146 134]
  ...
  [252 254 251]
  [252 254 251]
  [252 254 251]]

 [[168 150 138]
  [173 155 143]
  [163 147 134]
  ...
  [252 254 251]
  [252 254 251]
  [252 254 251]]]
